/* DO NOT EDIT THIS FILE - it is machine generated */
#include "..\include\jni.h"
/* Header for class com_github_dveonloch_ITM */

#ifndef _Included_com_github_dveonloch_ITM
#define _Included_com_github_dveonloch_ITM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_dveonloch_ITM
 * Method:    ITM_P2P_TLS
 * Signature: (DD[DIDDIDDIDDD)Lcom/github/dveonloch/ITMResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_dveonloch_ITM_ITM_1P2P_1TLS
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_github_dveonloch_ITM
 * Method:    ITM_P2P_TLS_Ex
 * Signature: (DD[DIDDIDDIDDD)Lcom/github/dveonloch/ITMIntermediateValuesResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_dveonloch_ITM_ITM_1P2P_1TLS_1Ex
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_github_dveonloch_ITM
 * Method:    ITM_P2P_CR
 * Signature: (DD[DIDDIDDIDD)Lcom/github/dveonloch/ITMResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_dveonloch_ITM_ITM_1P2P_1CR
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     com_github_dveonloch_ITM
 * Method:    ITM_P2P_CR_Ex
 * Signature: (DD[DIDDIDDIDD)Lcom/github/dveonloch/ITMIntermediateValuesResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_dveonloch_ITM_ITM_1P2P_1CR_1Ex
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     com_github_dveonloch_ITM
 * Method:    ITM_AREA_TLS
 * Signature: (DDIIDDIDDIDDIDDD)Lcom/github/dveonloch/ITMResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_dveonloch_ITM_ITM_1AREA_1TLS
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_github_dveonloch_ITM
 * Method:    ITM_AREA_TLS_Ex
 * Signature: (DDIIDDIDDIDDIDDD)Lcom/github/dveonloch/ITMIntermediateValuesResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_dveonloch_ITM_ITM_1AREA_1TLS_1Ex
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_github_dveonloch_ITM
 * Method:    ITM_AREA_CR
 * Signature: (DDIIDDIDDIDDIDD)Lcom/github/dveonloch/ITMResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_dveonloch_ITM_ITM_1AREA_1CR
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     com_github_dveonloch_ITM
 * Method:    ITM_AREA_CR_Ex
 * Signature: (DDIIDDIDDIDDIDD)Lcom/github/dveonloch/ITMIntermediateValuesResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_dveonloch_ITM_ITM_1AREA_1CR_1Ex
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
