/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class its_propagation_itm_ITM */

#ifndef _Included_its_propagation_itm_ITM
#define _Included_its_propagation_itm_ITM
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     its_propagation_itm_ITM
	 * Method:    ITMP2PTLS
	 * Signature: (DD[DIDDIDDIDDD)Lits/propagation/itm/ITMResult;
	 */
	JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITMP2PTLS
	(JNIEnv*, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

	/*
	 * Class:     its_propagation_itm_ITM
	 * Method:    ITMP2PTLSEx
	 * Signature: (DD[DIDDIDDIDDD)Lits/propagation/itm/ITMIntermediateValuesResult;
	 */
	JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITMP2PTLSEx
	(JNIEnv*, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

	/*
	 * Class:     its_propagation_itm_ITM
	 * Method:    ITMP2PCR
	 * Signature: (DD[DIDDIDDIDD)Lits/propagation/itm/ITMResult;
	 */
	JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITMP2PCR
	(JNIEnv*, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

	/*
	 * Class:     its_propagation_itm_ITM
	 * Method:    ITMP2PCREx
	 * Signature: (DD[DIDDIDDIDD)Lits/propagation/itm/ITMIntermediateValuesResult;
	 */
	JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITMP2PCREx
	(JNIEnv*, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

	/*
	 * Class:     its_propagation_itm_ITM
	 * Method:    ITMAREATLS
	 * Signature: (DDIIDDIDDIDDIDDD)Lits/propagation/itm/ITMResult;
	 */
	JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITMAREATLS
	(JNIEnv*, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

	/*
	 * Class:     its_propagation_itm_ITM
	 * Method:    ITMAREATLSEx
	 * Signature: (DDIIDDIDDIDDIDDD)Lits/propagation/itm/ITMIntermediateValuesResult;
	 */
	JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITMAREATLSEx
	(JNIEnv*, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

	/*
	 * Class:     its_propagation_itm_ITM
	 * Method:    ITMAREACR
	 * Signature: (DDIIDDIDDIDDIDD)Lits/propagation/itm/ITMResult;
	 */
	JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITMAREACR
	(JNIEnv*, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

	/*
	 * Class:     its_propagation_itm_ITM
	 * Method:    ITMAREACREx
	 * Signature: (DDIIDDIDDIDDIDD)Lits/propagation/itm/ITMIntermediateValuesResult;
	 */
	JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITMAREACREx
	(JNIEnv*, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
