/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class its_propagation_itm_ITM */

#ifndef _Included_its_propagation_itm_ITM
#define _Included_its_propagation_itm_ITM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     its_propagation_itm_ITM
 * Method:    ITM_P2P_TLS
 * Signature: (DD[DIDDIDDIDDD)Lits/propagation/itm/ITMResult;
 */
JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITM_1P2P_1TLS
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     its_propagation_itm_ITM
 * Method:    ITM_P2P_TLS_Ex
 * Signature: (DD[DIDDIDDIDDD)Lits/propagation/itm/ITMIntermediateValuesResult;
 */
JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITM_1P2P_1TLS_1Ex
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     its_propagation_itm_ITM
 * Method:    ITM_P2P_CR
 * Signature: (DD[DIDDIDDIDD)Lits/propagation/itm/ITMResult;
 */
JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITM_1P2P_1CR
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     its_propagation_itm_ITM
 * Method:    ITM_P2P_CR_Ex
 * Signature: (DD[DIDDIDDIDD)Lits/propagation/itm/ITMIntermediateValuesResult;
 */
JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITM_1P2P_1CR_1Ex
  (JNIEnv *, jclass, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     its_propagation_itm_ITM
 * Method:    ITM_AREA_TLS
 * Signature: (DDIIDDIDDIDDIDDD)Lits/propagation/itm/ITMResult;
 */
JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITM_1AREA_1TLS
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     its_propagation_itm_ITM
 * Method:    ITM_AREA_TLS_Ex
 * Signature: (DDIIDDIDDIDDIDDD)Lits/propagation/itm/ITMIntermediateValuesResult;
 */
JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITM_1AREA_1TLS_1Ex
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     its_propagation_itm_ITM
 * Method:    ITM_AREA_CR
 * Signature: (DDIIDDIDDIDDIDD)Lits/propagation/itm/ITMResult;
 */
JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITM_1AREA_1CR
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     its_propagation_itm_ITM
 * Method:    ITM_AREA_CR_Ex
 * Signature: (DDIIDDIDDIDDIDD)Lits/propagation/itm/ITMIntermediateValuesResult;
 */
JNIEXPORT jobject JNICALL Java_its_propagation_itm_ITM_ITM_1AREA_1CR_1Ex
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
